ShoppingApp/urls.py
from django.urls import path
from ShoppingApp import views
app_name="ShoppingApp"

urlpatterns = [
    path('',views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat, name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>',views.product, name='prodCatedetail'),
    path('login',views.login,name='login'),
    path('index',views.index,name='index'),
    # path('contact',views.contact,name='contact'),
    path('nav',views.nav,name='nav'),
    path('base',views.base,name='base')
    
]

cart/urls.py
from django.urls import path
from ShoppingApp.models import Product
from . import views
app_name="cart"
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name="add_cart"),
    path('',views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove')


]

search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'
urlpatterns = [
    path('',views.SearchResult, name='SearchResult'),
]

shopping_cart/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import  settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('ShoppingApp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/', include('cart.urls')),
    ]
if settings.DEBUG:
     urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
     urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ShoppingApp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class UserManage(models.Model):
    username =models.CharField(max_length=32, null=True, blank=True)
    password =models.CharField(max_length=32, null=True, blank=True)
    conformpassword =models.CharField(max_length=100, null=True, blank=True)
    
  
    class Meta:
        db_table='usermanage'
        
class Category(models.Model):
    name=models.CharField(max_length=100,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)
    
    class Meta:
        ordering=("name",)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('ShoppingApp:product_by_category', args=[self.slug])
        
    def __str__(self):
        return '{}'.format(self.name)
    
class Product(models.Model):
    name=models.CharField(max_length=250,unique=250)
    slug=models.SlugField(max_length=250,unique=250)
    description=models.TextField(max_length=250)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField()
    createdby=models.DateTimeField(auto_now=True)
    updatedby=models.DateField(auto_now=True)

    def get_url(self):
        return reverse('ShoppingApp:prodCatedetail', args=[self.category.slug,self.slug])
    
    class Meta:
        ordering=("name",)
        verbose_name='product'
        verbose_name_plural='products'
        
    def __str__(self):
        return '{}'.format(self.name)

cart/models.py
from django.db import models
from ShoppingApp.models import Product
# Create your models here.

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format( self.cart_id)

class CartItem(models.Model):
    product= models.ForeignKey(Product, on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table="CartItem"
    

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
       return '{}'.format(self.product)

search_app/models.py
from django.db import models

# Create your models here.

ShoppingApp/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from ShoppingApp.models import UserManage, Category, Product
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, InvalidPage
# Create your views here.

def home(request):
    return render(request,'index.html')
def log(request):
    return render(request,'login.html')    
def index(request):
    return render(request,'index.html')    
def nav(request):
    return render(request,'nav.html')
def login(request):
    return render(request,'login.html')
def register(request):
    return render(request,'register.html')
def base(request):
    return render(request,'base.html')



def allProdCat(request,c_slug=None):
    c_page=None
    products_lists=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_lists=Product.objects.all().filter(category=c_page, available=True)
    else:
        products_lists=Product.objects.all().filter(available=True)
    paginator=Paginator(products_lists,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage, InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,"category.html",{'category':c_page,'products':products})

def product(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html', {'product':product})

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ShoppingApp.models import Product
from . models import Cart , CartItem
from django.core.exceptions import  ObjectDoesNotExist

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:

            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request, total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items= CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))


def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity >1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

search_app/views.py
from django.shortcuts import render
from ShoppingApp.models import Product
from django.db.models import Q

# Create your views here.
def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query':query, "products":products})

templates/base.html
{% load static %}

<html lang="en">
    <head>
        
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
        <meta name="description" content="{% block metadescription %} {% endblock %}">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <div class="container">            
        </div>
    <div>
       {% include 'header.html' %}
       {% include 'nav.html' %}
       {% block content %}

    {% endblock %} </div>
       {% include 'footer.html' %}
       <script src="{% static 'js/popper.min.js' %}" ></script>
        <script src="{% static 'js/bootstrap.min.js' %}" ></script>

    </body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is shopping cart page. Proceed to review your items and place the order 
{% endblock %}

{% block title %} 
    cart - ABC Shopping center
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
    <div>
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart is empty
        </h1>
        <br>
        <p class="text-center">
            Please Click <a href="{% url 'ShoppingApp:allProdCat' %}">Here</a>to continue shopping.
        </p>
    </div>
</div>
{% else %}
<div>
    <div>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
        <br>
    </div>
</div>
<div class="row max-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        Your Items
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class ="float-left rounded custom_image"></a>
                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU: {{cart_item_product.id}}
                        <br>
                        Price: ${{cart_item.product.price}}
                        <br>
                        Qty: {{cart_item.quantity}} x $ {{cart_item}}
                    </td>
                    <td>
                        $ {{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a" ><i class="fa fa-plus custom_icon"></li></a>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></li></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></li></a>
                    </td>
                    {% else %}
                    {% comment %} <td>                        
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></li></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></li></a>
                    </td> {% endcomment %}
                </tr>
                {% endif %}
            {% endfor %}
            </tbody>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th>
                        Checkout
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Please review your shopping cart item before proceeding with the order payment
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'ShoppingApp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button"> Continue Shopping</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        welcome to ABC store where you can buy different items.........
    {% endif %}
{% endblock %}

{% block title %}    
{% if category %}
        {{ category.name}}- ABC store
    {% else %}
        see our new collection
    {% endif %}
{% endblock %}

{% block content %}
{% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx-auto">
            <p><a href="{% url 'ShoppingApp:allProdCat' %}">Our Product Collection</a></p>
        </div>
        </div>
    </div>
    {% endif %}
<div class="max_auto">
    {% if category %}
        <img src="{{ category.image.url }}" alt="{{category.name}}">

    <br>
            <h1>{{ category.name }}</h1>
            <p>{{ category.description }}</p>
</div>
    {% else %}
<div>
<center>
    <img src="{% static 'img/banner.png' %}" alt="our products" width="800px" height="350px">


</center>
     </div>
<br>
<div>
    <h1> our products collections</h1>
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
</div>
    {% endif %}
    <div>
        <div>
            {% for product in products %}
            <div>
                <div>
                    <a href=""><img src="{{product.image.url}}" alt="{{product.name}}">
                    <div>
                        <h4>{{product.name}}</h4>
                        <p>{{product.price}}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>

<div class="container">
    <div class="row mx_auto">
        {% for product in products %}

        <div class="my_bottom_margin col-9 col-sm-12 col-md-4">
            <div class="row">

            <div class="card text-center" style="width:400px;height:300px;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" style="width:45%;height:70%" src="{{product.image.url}}"
                                                   alt={{product.name}}""></a>
                <div class="card-body">
                    <div>Name:{{ product.name }}</div>
                    <div>Rs:{{ product.price }}</div>

                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    </div>
                    
<div class="max_auto">
    {% if products.paginator.num_pages > 1 %}
    <hr>
    <div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
</div>
{% endif %}
</div>
<br>
</div>

{% endblock%}

templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">@copy; All rights reserved</p>
</div>

templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'ShoppingApp:allProdCat' %}"> <img src="{% static 'img/logo1.jpg' %}" alt="logimage" width="100px" height="100px">
    </center>
</header>

templates/login.html
{% load static %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form class="user" action="/login-function" id="login" method="POST">

                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="text" name="Name" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Username" required>
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user" name="Password"
                                                id="exampleInputPassword" placeholder="Password" required>
                                        </div>
                                        <button type="submit" class="btn btn-primary btn-user btn-block" href="/bank-form">
                                            Login
                                        </button>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="/register">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

templates/nav.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">     
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">  
          <li class="nav-item">
            <a class="nav-link" href="/shop">Home</a>
          </li>
          <li class="nav-item dropdown {% if 'ShoppingApp' in request.path %} active {% endif %}">

           <a class="nav-link dropdown-toggle" href="{{cat.get_url}}" role="button" data-bs-toggle="dropdown" aria-expanded="false">

              Shop

            <ul class="dropdown-menu" aria-labelledby="navbar">
              <a class="dropdown-item" href="{% url 'ShoppingApp:allProdCat' %}">All products</a>
              {% for cat in links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}
            </ul>
           </a>
          </li>
          {% if item_count > 0 %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>{{item_count}}</a>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
          {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
          <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
        </form>
      </div>
    </div>
  </nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  
        {{ product.description|truncatewords:155 }}
    
        welcome to ABC store where you can buy different items.........
    
{% endblock %}
{% block title%}
{% if category %}
        {{ product.name}}- ABC store
    {% else %}
        see our new collection
    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="max_auto">
        <p> <a href="{% url 'ShoppingApp:allProdCat' %}"> Home</a> | <a href="{{product.category.get_url}}"> {{product.category}}</a>{{product.name}}</p>
    </div>
</div>
    <div  class="container">
    <br>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-md-12 col-lg-12 text-center">
            <div style="min-width:18rem">
                <img src="{{product.image.url}}" alt="{{product.name}}">
            </div>
        </div>
    <div>
    <div class="col-md-12 col-sm-12 col-md-12 col-lg-12">
        <div>
            <h3 class="my_prod_tittle">{{product.name}}</p></h3>  
            <p>${{product.price}}</p>     
            <p class="my_tittle">Product Description</p>  
            <p class="text-justity my_prod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justity my_prod_text"><b>Out of stock</b></p>
            {% else %}
            <a class= "btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
            {% endif %}
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    we have variety of products
{% endblock %}

{% block title %} 
    Search
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for : <br>"{{query}}"</p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}

        <div class="my_bottom_margin col-9 col-sm-12 col-md-4">
            <div class="row">

            <div class="card text-center" style="width:400px;height:300px;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" style="width:45%;height:70%" src="{{product.image.url}}"
                                                   alt={{product.name}}""></a>
                <div class="card-body">
                    <div>Name:{{ product.name }}</div>
                    <div>Rs:{{ product.price }}</div>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx_auto">
            <p class="text-center my_search_text"> 0 results found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}